services:
  database:
    image: 'mysql:latest'
    container_name: ldap_database_2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_ldap
    ports:
      - '3306'
  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin
    container_name: ldap_phpmyadmin_2
    restart: always
    ports:
      - '8382:80'
    environment:
      PMA_HOST: database